/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bank.system;

import static com.mycompany.bank.system.Data.businesses;
import static com.mycompany.bank.system.Data.users;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author RUMMON
 */
public class PayBill extends javax.swing.JFrame {

    /**
     * Creates new form PayBill
     */
    user Luser;

    public PayBill(user Luser) {
        initComponents();
        this.Luser = Luser;
//        jBalance.setText(Luser.balance + " TK");
        for (business i : businesses) {
            jBillid.addItem(i.comname);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBillid = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jBilltxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jAmount = new javax.swing.JTextField();
        jLogin = new javax.swing.JButton();
        jExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pay Bill");
        jLabel1.setFocusTraversalPolicyProvider(true);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Biller name:");

        jBillid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select one" }));
        jBillid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jBillidFocusLost(evt);
            }
        });
        jBillid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBillidActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Biller ID:");

        jBilltxt.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jBilltxt.setPreferredSize(new java.awt.Dimension(73, 30));
        jBilltxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jBilltxtFocusLost(evt);
            }
        });
        jBilltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBilltxtActionPerformed(evt);
            }
        });
        jBilltxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBilltxtKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Amount:");

        jAmount.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jAmount.setMinimumSize(new java.awt.Dimension(64, 30));
        jAmount.setName(""); // NOI18N
        jAmount.setPreferredSize(new java.awt.Dimension(71, 30));
        jAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAmountActionPerformed(evt);
            }
        });
        jAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jAmountKeyPressed(evt);
            }
        });

        jLogin.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jLogin.setText("Pay Bill");
        jLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginActionPerformed(evt);
            }
        });

        jExit.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jExit.setText("Exit");
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBilltxt, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                            .addComponent(jBillid, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(290, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jExit, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(266, 266, 266))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton2)
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBillid)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBilltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jLogin)
                .addGap(38, 38, 38)
                .addComponent(jExit)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new UserFrontPage(Luser).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jBilltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBilltxtActionPerformed
        // TODO add your handling code here:
        String id = jBilltxt.getText();
        int count = 0;
        for (business i : businesses) {
            count++;
            if (id.equals(i.comaccid)) {
                jBillid.setSelectedIndex(count);
            }
        }
    }//GEN-LAST:event_jBilltxtActionPerformed

    private void jAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAmountActionPerformed

    private void jLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginActionPerformed
        // TODO add your handling code here:
//        String billerId = jBillid.getSelectedItem().toString();
        String billerId = jBilltxt.getText();
        int currBalance = Integer.parseInt(Luser.balance);
//        String counter = jBilltxt.getText();
        int amount = Integer.parseInt(jAmount.getText());
        boolean flag = false;

        for (business i : businesses) {
            if (i.comaccid.equals(billerId)) {
                flag = true;
                if (currBalance > amount) {
                    //lessen this account tk

                    String bname = null;
                    business b = null;
                    for (user u : users) {
                        if (u.accId.equals(Luser.accId)) {
                            int newBalance = (currBalance - amount);
                            u.balance = Integer.toString(newBalance);
//                            jBalance.setText(u.balance + " TK");
                        }
                    }
                    //increase other account tk
                    for (business u : businesses) {
                        if (u.comaccid.equals(billerId)) {
                            int preBalance = Integer.parseInt(u.balance);
                            int newBalance = (preBalance + amount);
                            u.balance = Integer.toString(newBalance);
                            bname = u.comname;
                            b=u;
                        }
                    }
                    //call update database
                    System.out.println(".............updating txt file..........");
                    Data.update();
                    Data.updateBus();
                    JOptionPane.showMessageDialog(rootPane, amount + "TK paid to " + bname);
                    try {
                        PdfWithdrawbill.main(Luser, b, Integer.toString(amount));
                    } catch (IOException ex) {
                        Logger.getLogger(Withdraw.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    break;
                } else {
                    JOptionPane.showMessageDialog(rootPane, "You have not enough money");
                    break;
                }
            }
        }
        if (!flag) {
            JOptionPane.showMessageDialog(rootPane, "No account found with ID: " + billerId);
        }
    }//GEN-LAST:event_jLoginActionPerformed

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        // TODO add your handling code here:

        dispose();
    }//GEN-LAST:event_jExitActionPerformed

    private void jBillidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBillidActionPerformed
        // TODO add your handling code here:
        String cname = (String) jBillid.getSelectedItem();
        for (business i : businesses) {
            if (i.comname.equals(cname)) {
                jBilltxt.setText(i.comaccid);
            }
        }
    }//GEN-LAST:event_jBillidActionPerformed

    private void jBillidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jBillidFocusLost
        // TODO add your handling code here:         
    }//GEN-LAST:event_jBillidFocusLost

    private void jBilltxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jBilltxtFocusLost
        // TODO add your handling code here:
        String id = jBilltxt.getText();
        int count = 0;
        for (business i : businesses) {
            count++;
            if (id.equals(i.comaccid)) {
                jBillid.setSelectedIndex(count);
            }
        }
    }//GEN-LAST:event_jBilltxtFocusLost

    private void jBilltxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBilltxtKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)|| c == KeyEvent.VK_BACK_SPACE){
            jBilltxt.setEditable(false);
        }else{
            jBilltxt.setEditable(true);
        }
    }//GEN-LAST:event_jBilltxtKeyPressed

    private void jAmountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jAmountKeyPressed
       char c = evt.getKeyChar();
        if (Character.isDigit(c)|| c == KeyEvent.VK_BACK_SPACE){
            jAmount.setEditable(true);
        }else{
            jAmount.setEditable(false);
        }
    }//GEN-LAST:event_jAmountKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new PayBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAmount;
    private javax.swing.JComboBox<String> jBillid;
    private javax.swing.JTextField jBilltxt;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jLogin;
    // End of variables declaration//GEN-END:variables
}
